<template>
  <v-app>
    <Navbar />
    <v-main>
      <v-btn :icon="drawer ? 'mdi-menu-down' : 'mdi-menu-right'" @click="drawer = !drawer"></v-btn>
      <v-navigation-drawer v-model="drawer" app :width="240" align="left" location="left">
        <v-list-item link variant="plain" @click="selectContent('Overview')" title="Introduction"></v-list-item>
        <v-divider></v-divider>
        <v-list-item link variant="plain" @click="selectContent('Participants')" title="1. Participants"></v-list-item>
        <v-list-item link variant="plain" @click="selectContent('Phenotypes')" title="2. Imaging Traits"></v-list-item>
        <v-list-item link variant="plain" @click="selectContent('Processing')" title="3. Trait Processing"></v-list-item>
        <v-list-item link variant="plain" @click="selectContent('GWAS')" title="4. GWAS"></v-list-item>
        <v-list-item link variant="plain" @click="selectContent('Browser')" title="5. PheWeb2 Data"></v-list-item>
      </v-navigation-drawer>

      <div class="about-content" align="left">
        <div v-if="selectedContent === 'Overview'" id="Overview">
          <h2 class="text-center">About Imaging PheWeb</h2>
          <hr>
          <p>
            This platform presents genome-wide association (GWAS) and phenome-wide association (PheWAS) results from our genomic atlas of cardiac, adiposity, and bone imaging-derived phenotypes (IDPs). The following sections of the About page offer a brief description of the data preparation and analytical pipeline.
            If you have any specific questions or require more detailed information, please feel free to reach out. Our contact information is available on the Contact page.
          </p>
        </div>

        <div v-if="selectedContent === 'Participants'" id="Participants">
          <h2>1. Participants</h2>
          <hr>
          <p>
          Analyses were conducted among UK Biobank participants with imaging-derived phenotypes available in the v20 imaging release. Participants were excluded if they had withdrawn consent, discordance between self-reported and genetic sex, sex chromosome aneuploidy,
          excess heterozygosity or missingness, outlier flags, or missing whole-genome sequencing shipment-batch information.

          </p>
          <p>
            Trait-specific sample sizes were determined by imaging phenotype availability after quality control and
            covariate harmonization. The maximum analyzed sample size was 75,562 participants for cardiac MRI traits, 66,194 participants for DXA-derived adiposity traits,
            and 62,535 participants for DXA-derived bone traits.
          </p>
        </div>

        <div v-if="selectedContent === 'Phenotypes'" id="Phenotypes">
          <h2>2. Imaging Traits</h2>
          <hr>
          <p>
            We curated 97 quantitative IDPs from the UK Biobank v20 imaging release. For each participant, a single
            imaging instance was selected, prioritizing instance 2 and using instance 3 when instance 2 was unavailable.
          </p>
          <p>
            Cardiac traits comprised left ventricular structural, functional, and hemodynamic measures, together with
            body-surface-area-indexed derivatives. Adiposity traits comprised regional fat and lean mass measures,
            derived ratio traits, BMI- and height-adjusted fat and lean mass traits, and VAT-derived traits. Bone traits comprised bone mineral density (BMD), bone mineral content (BMC), and area.
          </p>
          <v-table density="compact" class="summary-table" hover>
            <colgroup>
              <col class="domain-column">
              <col class="numeric-column">
              <col class="numeric-column">
            </colgroup>
            <thead>
              <tr>
                <th>Domain</th>
                <th class="text-end">Traits</th>
                <th class="text-end">Maximum N</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Cardiac MRI</td>
                <td class="text-end">11</td>
                <td class="text-end">75,562</td>
              </tr>
              <tr>
                <td>DXA adiposity</td>
                <td class="text-end">31</td>
                <td class="text-end">66,194</td>
              </tr>
              <tr>
                <td>DXA bone</td>
                <td class="text-end">55</td>
                <td class="text-end">62,535</td>
              </tr>
            </tbody>
          </v-table>
        </div>

        <div v-if="selectedContent === 'Processing'" id="Processing">
          <h2>3. Trait Processing</h2>
          <hr>
          <p>
            Quantitative traits were generated by fitting trait-specific linear models and applying rank-based inverse
            normal transformation to the residuals. In pooled analyses, covariates included sex, age, age squared,
            sex-by-age terms, assessment center, WGS batch, and 20 genetic principal components.
          </p>
          <p>
            BMI- and height-adjusted adiposity traits additionally included BMI and height from the same imaging
            instance. Sex-stratified analyses used the same framework but omitted sex terms. Phenotypic correlations
            were calculated from observed phenotypic values rather than from the transformed residuals.
          </p>
        </div>

        <div v-if="selectedContent === 'GWAS'" id="GWAS">
          <h2>4. GWAS</h2>
          <hr>
          <p>
            Genome-wide association analyses used UK Biobank whole-genome sequencing data processed through the DRAGEN
            pipeline and converted to PLINK-compatible format. Analyses were restricted to autosomal bi-allelic A/C/G/T
            SNPs passing sample- and variant-level quality control.
          </p>
          <p>
            Association testing used REGENIE in a two-step framework. Step 1 fit whole-genome regression models to
            account for polygenic background, and step 2 tested single-variant associations for each residualized,
            normalized imaging phenotype. Pooled-sample summary statistics were used for primary discovery and most
            downstream analyses unless otherwise indicated.
          </p>
        </div>

        <div v-if="selectedContent === 'Browser'" id="Browser">
          <h2>5. PheWeb2 Data</h2>
          <hr>
          <p>
            Imaging PheWeb provides interactive access to association statistics across IDPs,
            including pooled and sex-stratified analyses where available. Users can browse phenotype-level results,
            variant pages, regional locus views, gene pages, PheWAS-style summaries, and top-hit tables.
          </p>
          <p>
            Downstream annotations in the browser may include credible-set information, candidate effector genes, and
            colocalization-supported shared loci, depending on availability for the queried locus or phenotype.
          </p>
        </div>
      </div>
    </v-main>
  </v-app>
</template>

<script setup name="About">
import Navbar from '@/components/Navbar.vue';
import { ref } from 'vue';

const selectedContent = ref('Overview');
const drawer = ref(true);

function selectContent(content) {
  selectedContent.value = content;
}
</script>

<style scoped>
.about-content {
  padding: 2%;
  max-width: 1100px;
}

.summary-table {
  max-width: 560px;
  margin-top: 1rem;
  border: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
  border-radius: 8px;
  overflow: hidden;
}

.summary-table :deep(th) {
  background: rgba(var(--v-theme-surface-variant), 0.22);
  color: rgba(var(--v-theme-on-surface), 0.9);
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.02em;
  text-transform: uppercase;
}

.summary-table :deep(td) {
  font-size: 0.92rem;
}

.domain-column {
  width: 55%;
}

.numeric-column {
  width: 22.5%;
}
</style>
